### PR TITLE
Remove nohup.out from src and add .gitignore

### PR DESCRIPTION
**Pull request by Wolfyxon**
Removed `nohup.out` since temp and log files should not be in the source code.
I also added a `.gitignore` file that will prevent this from happening again with some extra ignored files and dirs.

### CODE REVIEW

**Comment by Gmm09x** [comment]
Added temp folder for Temporary files and .gitignore all done thank you  for contributions

**Comment by Wolfyxon** [comment]
Well that's not how pull requests work. If you accept the contribution you have to merge it instead of closing the PR and doing the steps yourself. Also the gitignore provided by me also contains some files and dirs that should also be ignored.

**Comment by Gmm09x** [comment]
Im New in git and github I Only Know little bit but i'm learning consistent and i take care next time

**Comment by Wolfyxon** [comment]
> Im New in git and github I Only Know little bit but i'm learning consistent and i take care next time

Ah, it's fine.

**Pull request closed without merging**
